### ISSUE TITLE
Chores to bring in line with other eslint projects

### ISSUE THREAD

**Issue by corbinu** [eslint/eslint-scope#7]
I just wanted to create a list of chores that need to be done here please make suggestions @JamesHenry @nzakas 

- [x] Update README.md #3 
- [x] Remove unused bower.json #5 
- [x] Add eslint-release scripts #6 
- [x] Replace gulp with Makefile.js #15
- [x] Remove jsdoc #12 
- [x] Remove browserify #12 
- [x] Replace jshint with eslint #15
- [x] Remove es6-map and es6-weak-map as both are supported in Node 4 #14 
- [x] Remove Babel #9
- [x] Make eslint-config-eslint linting pass #15
- [x] Remove third_party directory #19
- [x] Remove esprima #19
- [x] Move src to lib folder

Was wondering what versions of node does eslint officially support? I would like to only downgrade the es6 as much as needed to make it run without Babel.

**Comment by nzakas** [comment]
We support Node 4 and higher. I'd love to get this to a point where it can run natively on Node so we can remove babel, though I'd set that as a longer-term goal.

**Comment by corbinu** [comment]
@nzakas Ok thanks

Also Node 4 or maintenance? (In other words is 5 supported and at what point after 8 drops does 7 support drop?)

**Comment by nzakas** [comment]
Node 4. We haven't made any other decisions regarding Node version support yet.

**Comment by soda0289** [comment]
I can help convert the gulpfile to Makefile.js and some other tasks.

**Comment by corbinu** [comment]
@JamesHenry @nzakas 
Just wondering if you guys have any other tasks you want done (or any tasks you think we can put off) before we can make a release of this and do a PR to replace escope in eslint. Hoping to get this in before 4.0

Not trying to rush you guys just having a very bad day as a tslint update appears to have broken linting on a bunch of my projects

**Comment by ilyavolodin** [comment]
@corbinu You still have a bit of time before we do 4.0 release. We usually cut a separate branch and do Release Candidates for a few weeks before we release new major version.

**Comment by corbinu** [comment]
@ilyavolodin Ok thanks ... either way if people could let me know if there is anything else they want in or wants to comment that any of these might not be needed for 4.0 please let me know :)

**Comment by soda0289** [comment]
After creating the Makefile.js I will also spend some time converting the code to pure es5/es6 instead of transcompiled with babel. After this it should be more easy to complete the rest of the tasks

**Comment by corbinu** [comment]
@soda0289 I have some time to work this weekend also do you want to toss me an email and we can plan it out.

**Comment by soda0289** [comment]
@corbinu I will probably start doing some work on the weekend. Haven't had enough time this week.

This is the order I think would work best.
1. Remove gulp as dependency and create Makefile.js. It will have to call babel to compile files and run tests. (Should be quick and easy)
2. Convert existing tests to es5/es6. Node v4 supports most es6 features. All we really need to do is replace imports/exports with require statement.
3. After tests are converted we can remove the third party directory and maybe create a test runner for the tests that will load espree. Update Makefile.js with new test runner.
4. Convert source code to es5/es6. Same idea as with the tests. Should be straight forward. We can divide up this work to save time. Source code should be moved to lib directory to align with other repositories.
5. Remove extra dependencies. Babel, jsdoc, es6-map, es6-weak-map, jshint
6. Add eslint with rules and fix linting errors. 

What are your thoughts? 

I will send you an email when I know I can make time to work on this. I feel like Saturday will be when I start writing the Makefile but that may change. WIll keep you updated.

**Comment by corbinu** [comment]
@soda0289 
Sounds good I actually already got the conversion to run on node 4 and the babel removal done. Lets sync up Saturday then on what needs to still be done.

**Comment by soda0289** [comment]
Nice Work! Should be pretty straight forward now. I will try and get Makefile.js done soon.

**Comment by corbinu** [comment]
Closing as all chores have been completed @JamesHenry As soon as a version is released on NPM I will open a PR for eslint to make the switch that way we can get the PR added to the 4 milestone
